### PR TITLE
added TextArea model

### PR DESCRIPTION
**Pull request by scattermagic**

### CODE REVIEW

**Comment by lynncyrin** [comment]
This is definitely that start, though quite a few more things would need to happen to get the text area rendering and saving in forms. I'll outline them later today

**Comment by lynncyrin** [comment]
Ok, other things this PR needs to do:

- add the model to admin https://github.com/project-callisto/django-wizard-builder/blob/96a12c322234927b8d77c18984acc7bbe4adb7a2/wizard_builder/admin/__init__.py
- add an inheritance test https://github.com/project-callisto/django-wizard-builder/blob/9eef126644ac63017b3a3fd0713dcfbfb152061f/wizard_builder/tests/test_inheritance.py
- add an admin test https://github.com/project-callisto/django-wizard-builder/blob/96a12c322234927b8d77c18984acc7bbe4adb7a2/wizard_builder/tests/test_admin.py
- be added to the text answer types https://github.com/project-callisto/django-wizard-builder/blob/97572b0ec47cedf848a3ade0b4dddb19764464e8/wizard_builder/view_helpers.py#L61

**Comment by scattermagic** [comment]
Ok great. Thanks for the direction. Getting the tests in django to work
took a bit of figuring out. I had to pip install a few things that were not
covered by 'make app-setup', I also had to download phantomjs and put it in
my .venv/bin folder. Maybe I missed a step that does all of that for you,
but if not, this should be mentioned in the develop.md file somewhere.
Anyway, I have the tests running now, so I will take a shot at adding the
text area to wizard builder

**Comment by lynncyrin** [comment]
@scattermagic 

> had to pip install a few things

perhaps this is addressed by https://github.com/project-callisto/django-wizard-builder/pull/190/commits/085a8f20a5f403a64d788eab52952c7a63820798 ?

> had to download phantomjs

added https://github.com/project-callisto/django-wizard-builder/pull/180/commits/a8ca4b57b53f079c1a7c98b77f84fa9a67cf1341

---

There's probably a few extra steps to the installation for phantomjs (than what my readme add hints at) but I'll leave it there for now

**Pull request closed without merging**
